MvcProject/Controllers/DoctorContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcProject.Models;

namespace MvcProject.Controllers
{
    public class DoctorContactController : Controller
    {
        // GET: DoctorContact
        DBModels db = new DBModels();
        public ActionResult Index(String p)
        {
            var degerler = from d in db.MESSAGEs select d;

            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.senderName.Contains(p));

            }
            return View(degerler.ToList());
        }
        public ActionResult DeleteMessage(int id)
        {
            var mesg = db.MESSAGEs.Find(id);
            db.MESSAGEs.Remove(mesg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AddMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMessage(MESSAGE d1)
        {
            db.MESSAGEs.Add(d1);
            db.SaveChanges();
            return View();
        }
    }
}

MvcProject/Views/DoctorContact/AddMessage.cshtml
<!DOCTYPE html>
<html>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">ÇAĞRI HASTANESİ</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="/DoctorAppointments/Index/">Randevular</a></li>
                        <li><a href="/DoctorContact/Index/">İletişim</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <br />
                        @using (Html.BeginForm("Logout", "DoctorLogin", FormMethod.Post))
                        {
                            <input type="submit" value="ÇIKIŞ YAP" />
                        }
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <br />
    <br />

    <center>
        <form class="form-group" method="post">
            <div>
                <label>Gönderen ID</label>
                <input type="text" class="form-control" name="senderID" />
            </div>
            <div>
                <label>Alıcı ID</label>
                <input type="text" class="form-control" name="receiverID" />
            </div>
            <div>
                <label>Gönderen Adı</label>
                <input type="text" class="form-control" name="senderName" />
            </div>
            <div>
                <label>Gönderen Soyadı</label>
                <input type="text" class="form-control" name="senderSurname" />
            </div>
            <div>
                <label>Alıcı Adı</label>
                <input type="text" class="form-control" name="receiverName" />
            </div>
            <div>
                <label>Alıcı Soyadı</label>
                <input type="text" class="form-control" name="receiverSurname" />
            </div>
            <div>
                <label>Mesaj İçeriği</label>
                <input type="text" class="form-control" name="messageContent" />
            </div>
            <div>
                <label>Mesaj Tarihi</label>
                <input type="text" class="form-control" name="messageDate" />
            </div>
            <div>
                <label>Mesaj Saati</label>
                <input type="text" class="form-control" name="messageHour" />
            </div>

            <div style="margin-top:15px">
                <button class="btn btn-info">Mesaj Ekle</button>
            </div>
        </form>
    </center>

</body>
</html>

MvcProject/Views/DoctorContact/Index.cshtml
@using MvcProject.Models;
@model List<MESSAGE>

<!DOCTYPE html>
<html>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">ÇAĞRI HASTANESİ</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="/DoctorAppointments/Index/">Randevular</a></li>
                        <li><a href="/DoctorContact/Index/">İletişim</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <br />
                        @using (Html.BeginForm("Logout", "DoctorLogin", FormMethod.Post))
                        {
                            <input type="submit" value="ÇIKIŞ YAP" />
                        }
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <br />
    <br />

    <head>
        <title> Çağrı Hastanesi </title>
        <style type="text/css">
            body {
                background-image: url("bg.jpg");
                background-size: cover;
            }

            #metin {
                text-align: justify;
                width: 1000px;
                word-wrap: break-word;
                margin: 0px auto;
                background: white;
                padding: 15px;
                border-style: solid;
                border-width: 2px;
                border-color: #8fc1da;
                line-height: 200%;
            }
        </style>
    </head>

    <div id="metin">
        <center>
            <h1><font style="font-family:Trebuchet MS; font-size:48px; color:#e80729;">MESAJLAR</font></h1>
        </center>
        <font style="font-family:Arial; font-size:18px; color:black;">
            <br />
            Mesajını görmek istediğiniz hastanın adını giriniz.
            <br />
            <br />

            @using (Html.BeginForm("Index", "DoctorContact", FormMethod.Get))
            {
                <p>
                    <center>
                        <b></b>Hasta Ara @Html.TextBox("p")
                        <br />
                        <br />
                        <input type="submit" class="btn btn-primary" value="Ara" />
                    </center>
                </p>
            }
            <br />

            <table class="table table-bordered">
                <tr>
                    <th>Gönderen ID</th>
                    <th>Gönderen Adı</th>
                    <th>Gönderen Soyadı</th>
                    <th>Alıcı Adı</th>
                    <th>Alıcı Soyadı</th>
                    <th>Mesaj İçeriği</th>
                    <th>Mesaj Tarihi</th>
                    <th>Mesaj Saati</th>
                    <th>SİL</th>
                </tr>

                <tbody>
                    @foreach (var ptn in Model)
                    {
                        <tr>
                            <td>@ptn.senderID</td>
                            <td>@ptn.senderName</td>
                            <td>@ptn.senderSurname</td>
                            <td>@ptn.receiverName</td>
                            <td>@ptn.receiverSurname</td>
                            <td>@ptn.messageContent</td>
                            <td>@ptn.messageDate</td>
                            <td>@ptn.messageHour</td>
                            <td><a href="/DoctorContact/DeleteMessage/@ptn.messageID" class="btn btn-danger">SİL</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />

            <center><a href="/DoctorContact/AddMessage/" class="btn btn-primary">Mesaj Ekle</a></center>
        </font>
    </div>
</body>
</html>