MvcProject/Controllers/AdminHomePatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcProject.Models;

namespace MvcProject.Controllers
{
    public class AdminHomePatientController : Controller
    {
        // GET: AdminHomePatient
        DBModels db = new DBModels();
        public ActionResult Index(String p)
        {
            var degerler = from d in db.PATIENTs select d;

            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.patientName.Contains(p));

            }
            return View(degerler.ToList());
        }
        public ActionResult DeletePatient(int id)
        {
            var ptn = db.PATIENTs.Find(id);
            db.PATIENTs.Remove(ptn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcProject/Views/AdminHomePatient/Index.cshtml
@using MvcProject.Models;
@model List<PATIENT>

<!DOCTYPE html>
<html>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">ÇAĞRI HASTANESİ</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="/AdminHome/Index/">Doktorlar</a></li>
                        <li><a href="/AdminHomePatient/Index/">Hastalar</a></li>
                        <li><a href="/AdminHomeAppointment/Index/">Randevu</a></li>
                        <li><a href="/AdminHomeFeedback/Index/">Geri Bildirim</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <br />
                        @using (Html.BeginForm("Logout", "AdminLogin", FormMethod.Post))
                        {
                            <input type="submit" value="ÇIKIŞ YAP" />
                        }
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <br />
    <br />

    @using (Html.BeginForm("Index", "AdminHomePatient", FormMethod.Get))
    {
        <p>
            <center>
                <b></b>Hasta Ara @Html.TextBox("p")
                <br />
                <br />
                <input type="submit" class="btn btn-primary" value="Ara" />
            </center>
        </p>
    }
    <br />

    <table class="table table-bordered">
        <tr>
            <th>Hasta ID</th>
            <th>Hasta Adı</th>
            <th>Hasta Soyadı</th>
            <th>Telefon Numarası</th>
            <th>Sil</th>
        </tr>

        <tbody>
            @foreach (var ptn in Model)
            {
                <tr>
                    <td>@ptn.patientID</td>
                    <td>@ptn.patientName</td>
                    <td>@ptn.patientSurname</td>
                    <td>@ptn.phoneNumber</td>
                    <td><a href="/AdminHomePatient/DeletePatient/@ptn.patientID" class="btn btn-danger">SİL</a></td>
                </tr>
            }
        </tbody>
    </table>
    <br />

</body>
</html>